# Generated by Django 5.2.17 on 2026-09-07 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('exchange', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('sector', models.CharField(blank=True, default='', max_length=150)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('business_summary', models.TextField(blank=True, default='')),
                ('full_time_employees', models.IntegerField(blank=True, null=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_affected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_logs', to='stocks.ticker')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('days_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('days_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('week52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('week52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='stocks.ticker')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_raw', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stocks.ticker')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='stocks.ticker')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'date'), name='unique_ticker_date')],
            },
        ),
    ]
